import AppKit
import SwiftUI
import CryptoKit

@MainActor
final class ClipboardStore: ObservableObject {
    @Published var items: [ClipItem] = []
    @Published var paused = false
    @Published var error: String?
    private var timer: Timer?
    private var lastChange = NSPasteboard.general.changeCount
    let directory: URL
    var imageDirectory: URL { directory.appendingPathComponent("Images", isDirectory: true) }
    private var defaults: UserDefaults { .standard }

    init() {
        UserDefaults.standard.register(defaults: ["recordText": true, "recordImages": true, "recordFiles": true, "historyLimit": 1000, "retentionDays": 30, "imageLimitMB": 20])
        directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].appendingPathComponent("ClipHarbor", isDirectory: true)
        do {
            try FileManager.default.createDirectory(at: imageDirectory, withIntermediateDirectories: true)
            let history = directory.appendingPathComponent("history.json")
            if FileManager.default.fileExists(atPath: history.path) {
                items = try JSONDecoder().decode([ClipItem].self, from: Data(contentsOf: history))
            }
            prune()
        } catch { self.error = "读取历史失败：\(error.localizedDescription)" }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
    }
    func poll() {
        let board = NSPasteboard.general
        guard board.changeCount != lastChange else { return }
        lastChange = board.changeCount
        guard !paused else { return }
        let excluded = defaults.string(forKey: "excludedApps") ?? ""
        let sourceApp = NSWorkspace.shared.frontmostApplication
        if excluded.split(separator: "\n").map({ $0.trimmingCharacters(in: .whitespaces) }).contains(sourceApp?.bundleIdentifier ?? "") { return }
        let sensitive = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        if sensitive.contains(where: { board.types?.contains(NSPasteboard.PasteboardType($0)) == true }) { return }
        var item: ClipItem?
        if defaults.bool(forKey: "recordFiles"),
           let urls = board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            item = ClipItem(kind: .files, fileURLs: urls, fileCategories: urls.map { FileCategory.classify($0).rawValue })
        } else if defaults.bool(forKey: "recordImages"),
                  let image = NSImage(pasteboard: board), let tiff = image.tiffRepresentation,
                  let bitmap = NSBitmapImageRep(data: tiff), let data = bitmap.representation(using: .png, properties: [:]) {
            let maxBytes = max(1, defaults.integer(forKey: "imageLimitMB")) * 1024 * 1024
            guard data.count <= maxBytes else { error = "图片超过设置的大小限制，未记录。"; return }
            let name = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined() + ".png"
            do { try data.write(to: imageDirectory.appendingPathComponent(name), options: .atomic) }
            catch { self.error = "保存图片失败：\(error.localizedDescription)"; return }
            item = ClipItem(kind: .image, imageName: name)
        } else if defaults.bool(forKey: "recordText"), let text = board.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard text.utf8.count <= 2 * 1024 * 1024 else { error = "文本超过 2 MB，未记录。"; return }
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            let url = URL(string: trimmed)
            let isLink = url?.host != nil && ["http", "https"].contains(url?.scheme?.lowercased() ?? "")
            item = ClipItem(kind: isLink ? .link : .text, text: text, richText: board.data(forType: .rtf))
        }
        guard var next = item else { return }
        next.source = sourceApp?.localizedName
        if let index = items.firstIndex(where: { $0.sameContent(as: next) }) {
            next = items.remove(at: index)
            next.date = Date()
        }
        items.insert(next, at: 0)
        prune()
        save()
    }
    func prune() {
        let limit = max(1, defaults.integer(forKey: "historyLimit"))
        let days = defaults.integer(forKey: "retentionDays")
        let cutoff = Date().addingTimeInterval(-Double(days) * 86400)
        var count = 0
        items.removeAll { item in
            if item.favorite { return false }
            count += 1
            return count > limit || (days > 0 && item.date < cutoff)
        }
        cleanupImages()
    }
    func save() {
        do {
            let data = try JSONEncoder().encode(items)
            try data.write(to: directory.appendingPathComponent("history.json"), options: .atomic)
        } catch { self.error = "保存历史失败：\(error.localizedDescription)" }
    }
    func toggleFavorite(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].favorite.toggle(); save()
    }
    func setNote(_ id: UUID, _ note: String) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].note = note; save()
    }
    func delete(_ ids: Set<UUID>) { items.removeAll { ids.contains($0.id) }; save(); cleanupImages() }
    func clear(keepFavorites: Bool) { items.removeAll { !keepFavorites || !$0.favorite }; save(); cleanupImages() }
    private func cleanupImages() {
        let kept = Set(items.compactMap(\.imageName))
        for url in (try? FileManager.default.contentsOfDirectory(at: imageDirectory, includingPropertiesForKeys: nil)) ?? [] where !kept.contains(url.lastPathComponent) {
            try? FileManager.default.removeItem(at: url)
        }
    }
    func copy(_ item: ClipItem, plain: Bool = false) -> Bool {
        let board = NSPasteboard.general
        if item.kind == .files {
            guard item.fileURLs.allSatisfy({ FileManager.default.fileExists(atPath: $0.path) }) else { error = "原文件不可用，请检查文件位置。"; return false }
            board.clearContents()
            guard board.writeObjects(item.fileURLs.map { $0 as NSURL }) else { error = "复制文件失败。"; return false }
        } else if let name = item.imageName {
            guard let image = NSImage(contentsOf: imageDirectory.appendingPathComponent(name)) else { error = "图片缓存不可用。"; return false }
            board.clearContents(); board.writeObjects([image])
        } else {
            board.clearContents()
            board.setString(item.text ?? "", forType: .string)
            if !plain, let rtf = item.richText { board.setData(rtf, forType: .rtf) }
        }
        lastChange = board.changeCount
        return true
    }
}
